dist: trusty
language: node_js
services:
  - postgresql
addons:
  postgresql: "11.4"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - sleep 5
  - psql --version
  - psql -U postgres -a -f ./server/sql/createDatabase.sql
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - psql -U postgres -a -f ./server/sql/createTable.sql
node_js:
  - "10"
env:
  global:
    - PGPORT='5432'
    - NODE_ENV=test
    - PGhost='127.0.0.1'
    - PGpassword=''
    - PGport='5432'
    - PGuser='postgres'
    - PGdatabaseName='postgres'
    - jwtSecret='test.KinGtoCtURNaPHeRGArABarkrArdWEldSperFultRaTCheISTU'
install:
  - npm install
script:
  npm run test
after_success:
  - npm run coverage
deploy:
  provider: heroku
  app: way-farer
  on:
    branch: master
  api_key:
    secure: "Xq6RJFjzSb+S1fX1BIb/zrIEigZ9uDr3NxKUFO8vhUBMhjJX8B+bhwebH7x3HXXNfmk/vs+UFyVGYvbkRcZleqyXcu65WE4+Y91eXYWroex7etCg3kgQi5uI0Hl3cpUj3EZZ62sJBKwoOmbef11+wrl/Id5PRlwBrZ9rou9km1vOm0gmYG8yViu7CDz8pdBnFGDEIRSUnjUB3NIE1mCyfnh2yUpE3PD5e2MqieWeIllxUAhfvjqlhb+MAgNThEgZ9Plg41PnsPiEfE3GhRbkjrr7pkEMYpTSxZ6Sti7D4wvbmcsbcZeTP/FetyaskAW96q1GBAuALMs1Kv4kNogzZLE23ogOfQZQLAHQ4zSEh7K9FkfEBbDjyC2Ma91uxY2Z1jIYDGXkm85WmSW01pYX1Tau2OcThnGWDC+5DBXPtc/O2Keuy+RSDkp83+SkP9oSTyjAhc9yNWXn+fkkCN80SmfX2Oq1cR788QHDcp8AaXurYjz759EoIeuPqr69mjImNz3c061V+74iJDc/MfmAAs2s8KC9PMrbLPJ3APBdVDtisEeTG/zU0F4Xg6lPHhJxy343VECxauB9ILkrpJV5EK1NuWbO3DalAfI00FJ2uO/rD3syr36Az95V5cJZblqKt+1AEkjs4ObqssPINM7GBpmY8POLcaBa79BYfxAxxn8="
